steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'web', 'cloudbuildhello/gowebhello']
  env: ['PROJECT_ROOT=cloudbuildhello']
artifacts:
  objects:
    location: 'gs://cloudbuildhello/'
    paths: ['web', './sample_artifact.txt']
