steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['test', 'cloudbuildhello/gowebhello']
  env: ['PROJECT_ROOT=cloudbuildhello']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-v', '-o', 'webd', 'cloudbuildhello/gowebhello']
  env: ['PROJECT_ROOT=cloudbuildhello']
artifacts:
  objects:
    location: 'gs://cloudbuildhello/'
    paths: ['webd', './sample_artifact.txt']
